//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLIGHT()
        {
            this.JOURNEYFLIGHT = new HashSet<JOURNEYFLIGHT>();
        }
    
        public int ID { get; set; }
        public int TRANSPORT_ID { get; set; }
        public string ORIGIN { get; set; }
        public string DESTINATION { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual TRANSPORT TRANSPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNEYFLIGHT> JOURNEYFLIGHT { get; set; }
    }
}
